### ISSUE TITLE
Music Genre Classification Demo

### ISSUE THREAD

**Issue by NripeshN** [ivy-llc/demos#77]
**Objective:** Develop a machine learning model capable of classifying music into different genres based on audio features such as tempo, pitch, and timbre using ivy. This project is an exciting opportunity for music enthusiasts to combine their passion for music with machine learning to create a model that can help in understanding and categorizing music more effectively.

**Task Details:**

- **Dataset:** For this task, you'll be using the GTZAN Dataset, available at this link: [GTZAN Dataset for Music Genre Classification](https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification). This dataset includes audio files across various music genres, providing a diverse range of audio features for training your model.

- **Expected Output:** Your submission should include a Jupyter notebook that outlines the model development process, including data preprocessing, feature extraction from audio files, model training, and evaluation. Please also include the trained model files alongside the notebook.

- **Submission Directory:** Place your completed Jupyter notebook and model files in the `Contributor_demos/Music Genre Classification` subdirectory within the `unifyai/demos` repository.

**How to Contribute:**

1. Fork the `unifyai/demos` repository to your GitHub account.
2. Clone your forked repository to your local machine.
3. Create a new branch specifically for your work on this use case.
4. Proceed to develop your model and document the process in the Jupyter notebook as outlined in the task details.
5. Save your notebook and model files in the `Contributor_demos/Music Genre Classification` directory.
6. After completing your work, push the changes to your forked repository.
7. Submit a Pull Request (PR) to the `unifyai/demos` repository with a clear title indicating the use case, such as "Music Genre Classification Demo Submission".

**Contribution Guidelines:**

- Ensure your code is clearly documented for ease of understanding and replication.
- In your PR description, provide a concise summary of your approach, key insights gained, and any obstacles you overcame during the project.

**Comment by abhi2596** [comment]
#95
