### ISSUE TITLE
Chest X-Ray Images (Pneumonia) Detection Demo(Intermediate)

### ISSUE THREAD

**Issue by NripeshN** [ivy-llc/demos#91]
**Objective:** Construct a machine learning model using ivy that can accurately diagnose pneumonia from chest X-ray images. This project seeks to harness the capabilities of deep learning in medical imaging, offering a tool that could potentially assist radiologists and healthcare providers in the early detection and treatment of pneumonia.

**Task Details:**

- **Dataset:** This project will utilize the Chest X-Ray Images (Pneumonia) dataset available on Kaggle, which can be found here: [Chest X-Ray Images (Pneumonia) Dataset](https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia). The dataset contains a large number of X-ray images categorized into pneumonia and normal conditions, providing a valuable resource for training and testing the diagnostic model.

- **Expected Output:** Contributors are expected to deliver a Jupyter notebook that outlines the model development process in detail, from image preprocessing and augmentation to model training, validation, and testing. The submission should also include the trained model files.

- **Submission Directory:** Please place your completed Jupyter notebook and any related model files in the `Contributor_demos/Chest X-Ray Images (Pneumonia)` subdirectory within the `unifyai/demos` repository.

**How to Contribute:**

1. Fork the `unifyai/demos` repository to your GitHub account.
2. Clone your forked repository to your local machine.
3. Create a new branch specifically for your work on the Chest X-Ray Images (Pneumonia) Detection demo.
4. Develop your model, ensuring comprehensive documentation of the process in the Jupyter notebook.
5. Save your notebook and model files in the `Contributor_demos/Chest X-Ray Images (Pneumonia)` directory.
6. Once your work is complete, push your branch to your forked repository.
7. Submit a Pull Request (PR) to the `unifyai/demos` repository, clearly indicating the project in the title, such as "Chest X-Ray Images (Pneumonia) Detection Demo Submission".

**Contribution Guidelines:**

- Ensure your code is well-documented, facilitating understanding and ease of replication.
- Summarize your approach, key insights, and any significant challenges encountered in the PR description, providing a clear overview of your project journey.

**Review and Feedback:**

Submissions will be reviewed on an ongoing basis. Feedback or requests for modifications will be communicated through the PR discussion. The project maintainers will merge your contribution once it aligns with the project's standards and objectives, making a valuable contribution to the application of machine learning in healthcare.

This project offers a significant opportunity to impact public health positively by advancing the capabilities of AI in medical diagnostics. We look forward to your innovative solutions and contributions towards improving pneumonia detection through deep learning.

**Comment by leebissessar5** [comment]
Working on this.
